### ISSUE TITLE
translate your fucking doc

### ISSUE THREAD

**Issue by dowan** [ResolveWang/WeiboSpider#24]
hi

**Comment by ResolveWang** [comment]
My english is not so good, I hope someone can help to do this job

**Comment by cyber60J** [comment]
I may help you with the translation. Where is the content?

**Comment by ResolveWang** [comment]
At the beginning, I thought most of the users were Chinese people, so the doc was written in Chinese. Now if someone can translate the readme into english,I will really appreciate it. And I hope the guy is also a user of the project

**Comment by cyber60J** [comment]
I am willing to help. By the way, the subject line is really rude and
disrespectful. I was shocked at first time.

**Comment by ResolveWang** [comment]
Thanks. It's just a suggestion and ist's reasonable.Don't think too much.

**Comment by stefanos82** [comment]
I have expressed my own complain on another project that it was as well written in Chinese.

It's a shame you know, because this way it feels like we are not helping each other out and it's a sad thing to witness.

All this knowledge to stay in the shadows due to non-standard human language.

To give you an idea @ResolveWang, the majority of us (around the globe that is) don't speak English as our first language and we **do** make mistakes all the time. Still though, we use it to communicate with each other.

So please...translate the darn thing lol!

Cheers.

**Comment by ResolveWang** [comment]
Yeah,I will translate the doc into English in my free time recently.Thanks for your advice.
